name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/APIIntegrationAndroidTests/APIServiceTest.kt -o app/src/test/java/com/ifood/deliveryapp/APIServiceTest.kt

      - name: Run Unit Tests
        run: ./gradlew test